
; Generated by CharPad C64 - Subchrist Software, 2003 - 2023.
; Assemble with 64TASS or similar.


; Display mode : Text (Multi-colour).
; Matrix colouring method : Per Project.


; Colour values...

COLR_VIC_BG0 = 6
COLR_VIC_BG1 = 0
COLR_VIC_BG2 = 7
COLR_CMLO_BASE = 10


; Quantities and dimensions...

CHAR_COUNT = 256
TILE_COUNT = 32
TILE_WID = 2
TILE_HEI = 2
MAP_WID = 15
MAP_HEI = 10
MAP_WID_CHRS = 30
MAP_HEI_CHRS = 20
MAP_WID_PXLS = 240
MAP_HEI_PXLS = 160


; Data block sizes (in bytes)...

SZ_CHARSET_DATA = 2048 ; ($800)
SZ_CHARSET_ATTRIB_DATA = 256 ; ($100)
SZ_TILESET_DATA = 128 ; ($80)
SZ_MAP_DATA = 150 ; ($96)


; Data block addresses (dummy values)...

addr_charset_data = $1000
addr_charset_attrib_L1_data = $1000
addr_chartileset_data = $1000
addr_chartileset_tag_data = $1000
addr_map_data = $1000




; * INSERT EXAMPLE PROGRAM HERE! * (or just include this file in your project).




; CharSet Data...
; 256 images, 8 bytes per image, total size is 2048 ($800) bytes.

* = addr_charset_data
charset_data




; CharSet Attribute (L1) Data...
; 256 attributes, 1 attribute per image, 8 bits per attribute, total size is 256 ($100) bytes.
; nb. Upper nybbles = material, lower nybbles = unused.

* = addr_charset_attrib_L1_data
charset_attrib_L1_data

.byte $00,$10,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00



; CharTileSet Data...
; 32 tiles, 2x2 (4) cells per tile, 8 bits per cell, total size is 128 ($80) bytes.

* = addr_chartileset_data
chartileset_data

.byte $60,$62,$70,$72,$4D,$4E,$5D,$5E,$67,$68,$77,$78,$60,$61,$70,$71
.byte $61,$62,$71,$72,$6B,$6C,$7B,$7C,$7F,$6F,$7B,$7C,$00,$00,$90,$91
.byte $00,$00,$91,$91,$00,$00,$91,$92,$00,$00,$00,$00,$82,$00,$80,$91
.byte $00,$83,$91,$81,$82,$00,$82,$00,$00,$83,$00,$83,$85,$91,$82,$00
.byte $91,$84,$00,$83,$91,$91,$00,$00,$B0,$A0,$B0,$B0,$B0,$B0,$B0,$B0
.byte $A2,$B0,$B0,$B0,$B0,$B0,$B0,$A3,$A1,$B0,$B0,$B0,$40,$41,$50,$51
.byte $42,$43,$52,$53,$44,$45,$54,$55,$46,$47,$56,$57,$48,$49,$58,$59
.byte $4A,$4B,$5A,$5B,$4C,$00,$5C,$4C,$00,$00,$00,$00,$00,$00,$00,$00



; CharTileSet Tag Data...
; 32 tags, 1 per tile, 8 bits each, total size is 32 ($20) bytes.

* = addr_chartileset_tag_data
chartileset_tag_data

.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00



; Map Data...
; 15x10 (150) cells, 8 bits per cell, total size is 150 ($96) bytes.




