//////////////////////////////////////////////////////////////////////////////////////
// DATA TABLES & STUFF
//////////////////////////////////////////////////////////////////////////////////////
data_titlefloridaman:
.byte 64,65,68,69,72,73,76,77,80,81,84,85,88,89
.byte 66,67,70,71,74,75,78,79,82,83,86,87,90,91
.byte 32,32,32,32,92,93,88,89,96,97,32,32,32,32
.byte 32,32,32,32,94,95,90,91,98,99,32,32,32,32
data_titlefloridamancolor:

.byte LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE
.byte LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE
.byte YELLOW,YELLOW,YELLOW,LIGHT_BLUE,LIGHT_BLUE,LIGHT_BLUE,YELLOW,YELLOW,LIGHT_BLUE,LIGHT_BLUE, BLUE,YELLOW,YELLOW,YELLOW
.byte YELLOW,YELLOW,YELLOW,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,  BLUE,YELLOW,YELLOW,YELLOW,YELLOW

.byte DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY // 14 bytes
.byte DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY
.byte DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY
.byte DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY,LIGHT_GRAY,WHITE,LIGHT_GRAY,GRAY,DARK_GRAY,GRAY
